update workflow for env secret

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -7,31 +7,32 @@ on:
 
 jobs:
   test:
-    name: Run Tests
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout code
-        uses: actions/checkout@v4
+        uses: actions/checkout@v3
 
       - name: Set up Python
-        uses: actions/setup-python@v5
+        uses: actions/setup-python@v4
         with:
-          python-version: '3.x'
+          python-version: '3.9'
 
       - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
+        run: pip install -r requirements.txt
 
-      - name: Run Tests
-        run: pytest --junit-xml=junit.xml -o junit_family=xunit1
+      - name: Run tests with pytest
+        run: pytest --junitxml=report.xml
 
-      - name: Upload Test Results to Trunk.io
-        if: '!cancelled()' # Upload the results even if the tests fail
-        continue-on-error: true # don't fail this job if the upload fails
-        uses: trunk-io/analytics-uploader@v1
+      - name: Upload results
+        # Run this step even if the test step ahead fails
+        if: success() || failure()
+        uses: trunk-io/analytics-uploader@main
         with:
-          junit-paths: "**/junit.xml"
-          org-slug: <TRUNK_ORG_URL_SLUG>
+          # Path to your test results.
+          junit-paths: "**/*.xml"
+          # Provide your Trunk organization slug.
+          # Can use a GitHub secret.
+          org-slug: ${{ secrets.TRUNK_ORG_URL_SLUG }}
+          # Provide your Trunk API token as a GitHub secret.
           token: ${{ secrets.TRUNK_API_TOKEN }}
+        continue-on-error: true
